# Generated by Django 3.1.6 on 2021-02-20 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DonneCommune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('identifiant', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('donnecommune_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banks.donnecommune')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=50)),
            ],
            bases=('banks.donnecommune',),
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('donnecommune_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banks.donnecommune')),
                ('statut_moral', models.CharField(max_length=50)),
            ],
            bases=('banks.donnecommune',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('donnecommune_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banks.donnecommune')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=50)),
                ('compte', models.CharField(max_length=25)),
                ('montant', models.CharField(max_length=50)),
            ],
            bases=('banks.donnecommune',),
        ),
    ]
