# Generated by Django 3.1.6 on 2021-02-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_auto_20210220_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='montant',
            field=models.IntegerField(),
        ),
    ]
