# Generated by Django 3.1.6 on 2021-02-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_auto_20210220_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnecommune',
            name='email',
            field=models.EmailField(max_length=225),
        ),
        migrations.AlterField(
            model_name='donnecommune',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
