# Generated by Django 3.1.6 on 2021-02-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_auto_20210220_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnecommune',
            name='numero',
            field=models.ImageField(upload_to=''),
        ),
    ]
